# Generated by Django 3.0.8 on 2020-08-02 07:44

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('Location', models.TextField(max_length=100)),
                ('CameraID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('X_coordinate', models.IntegerField()),
                ('Y_corrdinate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarRTO',
            fields=[
                ('Brand', models.CharField(max_length=20)),
                ('Owner', models.CharField(max_length=30)),
                ('DateRegistered', models.DateTimeField(auto_now_add=True)),
                ('CarModel', models.CharField(max_length=20)),
                ('PlateNumber', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('CrimeRecord', models.CharField(max_length=1000, null=True)),
                ('LastPollutionCheck', models.DateTimeField()),
                ('LastInsuranceRenew', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CarSurveillance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=10)),
                ('CarModel', models.CharField(max_length=20)),
                ('PlateNumber', models.CharField(max_length=20)),
                ('Brand', models.CharField(max_length=20)),
                ('CameraID', models.CharField(max_length=10)),
                ('Imagename', models.CharField(max_length=20)),
                ('VideoTimeStamp', models.CharField(max_length=20)),
                ('VideoFPS', models.IntegerField(default=60)),
                ('Videoname', models.CharField(max_length=20)),
                ('Seen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ImageName', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('CrimeRecord', models.TextField()),
                ('IsLicensed', models.BooleanField()),
                ('Name', models.CharField(max_length=20)),
                ('VehiclesRegistered', django_mysql.models.ListTextField(models.CharField(max_length=20), size=10)),
                ('PersonId', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
