# Generated by Django 3.0.8 on 2020-08-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='Y_corrdinate',
            new_name='Y_coordinate',
        ),
        migrations.AlterField(
            model_name='carrto',
            name='DateRegistered',
            field=models.DateField(),
        ),
    ]
