# Generated by Django 3.0.8 on 2020-08-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20200803_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarRTO',
        ),
    ]
