# Generated by Django 3.0.8 on 2020-08-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_delete_carrto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRTO',
            fields=[
                ('Brand', models.CharField(max_length=20)),
                ('Owner', models.CharField(max_length=30)),
                ('DateRegistered', models.DateField()),
                ('CarModel', models.CharField(max_length=20)),
                ('PlateNumber', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('CrimeRecord', models.CharField(max_length=1000, null=True)),
                ('LastPollutionCheck', models.DateTimeField()),
                ('LastInsuranceRenew', models.DateTimeField()),
            ],
        ),
    ]
